package com.aula.virtual.domain;
// Generated 24-sep-2016 8:54:56 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnioAsignaturaId generated by hbm2java
 */
@Embeddable
public class AnioAsignaturaId implements java.io.Serializable {

	private int idAnio;
	private int idAsignatura;

	public AnioAsignaturaId() {
	}

	public AnioAsignaturaId(int idAnio, int idAsignatura) {
		this.idAnio = idAnio;
		this.idAsignatura = idAsignatura;
	}

	@Column(name = "ID_ANIO", nullable = false)
	public int getIdAnio() {
		return this.idAnio;
	}

	public void setIdAnio(int idAnio) {
		this.idAnio = idAnio;
	}

	@Column(name = "ID_ASIGNATURA", nullable = false)
	public int getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(int idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnioAsignaturaId))
			return false;
		AnioAsignaturaId castOther = (AnioAsignaturaId) other;

		return (this.getIdAnio() == castOther.getIdAnio()) && (this.getIdAsignatura() == castOther.getIdAsignatura());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAnio();
		result = 37 * result + this.getIdAsignatura();
		return result;
	}

}
