package com.aula.virtual.domain;
// Generated 24-sep-2016 8:54:56 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AnioAsignatura generated by hbm2java
 */
@Entity
@Table(name = "anio_asignatura", catalog = "AULA_VIRTUAL")
public class AnioAsignatura implements java.io.Serializable {

	private AnioAsignaturaId id;

	public AnioAsignatura() {
	}

	public AnioAsignatura(AnioAsignaturaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idAnio", column = @Column(name = "ID_ANIO", nullable = false)),
			@AttributeOverride(name = "idAsignatura", column = @Column(name = "ID_ASIGNATURA", nullable = false)) })
	public AnioAsignaturaId getId() {
		return this.id;
	}

	public void setId(AnioAsignaturaId id) {
		this.id = id;
	}

}
