package com.aula.virtual.domain;
// Generated 24-sep-2016 8:54:56 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AnioAsignaturaDocente generated by hbm2java
 */
@Entity
@Table(name = "anio_asignatura_docente", catalog = "AULA_VIRTUAL")
public class AnioAsignaturaDocente implements java.io.Serializable {

	private AnioAsignaturaDocenteId id;

	public AnioAsignaturaDocente() {
	}

	public AnioAsignaturaDocente(AnioAsignaturaDocenteId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idAnio", column = @Column(name = "ID_ANIO", nullable = false)),
			@AttributeOverride(name = "idAsignatura", column = @Column(name = "ID_ASIGNATURA", nullable = false)),
			@AttributeOverride(name = "idDocente", column = @Column(name = "ID_DOCENTE", nullable = false)) })
	public AnioAsignaturaDocenteId getId() {
		return this.id;
	}

	public void setId(AnioAsignaturaDocenteId id) {
		this.id = id;
	}

}
