package com.aula.virtual.domain;
// Generated 24-sep-2016 8:54:56 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "AULA_VIRTUAL")
public class Docente implements java.io.Serializable {

	private Integer idDocente;
	private String nombre;
	private String apellido;
	private String imagen;
	private Integer idUsuario;

	public Docente() {
	}

	public Docente(String nombre, String apellido) {
		this.nombre = nombre;
		this.apellido = apellido;
	}

	public Docente(String nombre, String apellido, String imagen, Integer idUsuario) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.imagen = imagen;
		this.idUsuario = idUsuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_DOCENTE", unique = true, nullable = false)
	public Integer getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(Integer idDocente) {
		this.idDocente = idDocente;
	}

	@Column(name = "NOMBRE", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "APELLIDO", nullable = false, length = 45)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "IMAGEN", length = 45)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "ID_USUARIO")
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

}
