package com.aula.virtual.domain;
// Generated 24-sep-2016 8:54:56 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Semana generated by hbm2java
 */
@Entity
@Table(name = "semana", catalog = "AULA_VIRTUAL")
public class Semana implements java.io.Serializable {

	private Integer idSemana;
	private String descripcion;

	public Semana() {
	}

	public Semana(String descripcion) {
		this.descripcion = descripcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_SEMANA", unique = true, nullable = false)
	public Integer getIdSemana() {
		return this.idSemana;
	}

	public void setIdSemana(Integer idSemana) {
		this.idSemana = idSemana;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
